export enum KitaNetzLANDOpts {
    Baden_Württemberg = "Baden-Württemberg",
    Bayern = "Bayern",
    Berlin = "Berlin",
    Brandenburg = "Brandenburg",
    Bremen = "Bremen",
    Hamburg = "Hamburg",
    Hessen = "Hessen",
    Mecklenburg_Vorpommern = "Mecklenburg-Vorpommern",
    Niedersachsen = "Niedersachsen",
    Nordrhein_Westfalen = "Nordrhein-Westfalen",
    Rheinland_Pfalz = "Rheinland-Pfalz",
    Saarland = "Saarland",
    Sachsen = "Sachsen",
    Sachsen_Anhalt = "Sachsen-Anhalt",
    Schleswig_Holstein = "Schleswig-Holstein",
    Thüringen = "Thüringen",
}